# Setup
title:        William Watkins
tagline:      A portfolio for 42 projects
baseurl:      ""
paginate:     10

# About/contact
author:
  name:       William Watkins
  url:        http://wwatkins42.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
